services:
  db:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - vol-pgdata:/var/lib/postgresql/data
      - ./container/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "ny_taxi", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "8080:80"
    volumes:
      - vol-pgadmin_data:/var/lib/pgadmin

  minio:
    image: minio/minio:latest
    command: ["server", "--console-address", ":9001", "/data"]
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - vol-minio_data:/data
    env_file:
      - ./container/minio/.env
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-bootstrap:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    env_file:
      - ./container/minio/.env
    volumes:
      - ./container/minio/minio-bootstrap.sh:/minio-bootstrap.sh:ro
    entrypoint: /bin/sh
    command: ["-c", "/minio-bootstrap.sh"]
    restart: no

volumes:
  vol-pgdata:
    name: vol-pgdata
  vol-pgadmin_data:
    name: vol-pgadmin_data
  vol-minio_data:
    name: vol-minio_data
