version: 2

sources:
  - name: staging
    database: de-zoomcamp-411717
    schema: nytaxi

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}
      - name: fhv_tripdata
