taxi_dtypes = {
    "yellow": {
        "VendorID": "Int64",
        "passenger_count": "Int64",
        "trip_distance": "Float64",
        "RatecodeID": "Float64",
        "store_and_fwd_flag": "string",
        "PULocationID": "Int64",
        "DOLocationID": "Int64",
        "payment_type": "Int64",
        "fare_amount": "Float64",
        "extra": "Float64",
        "mta_tax": "Float64",
        "tip_amount": "Float64",
        "tolls_amount": "Float64",
        "improvement_surcharge": "Float64",
        "total_amount": "Float64",
        "congestion_surcharge": "Float64",
    },
    "green": {
        "VendorID": "Int64",
        "store_and_fwd_flag": "string",
        "RatecodeID": "Float64",
        "PULocationID": "Int64",
        "DOLocationID": "Int64",
        "passenger_count": "Int64",
        "trip_distance": "Float64",
        "fare_amount": "Float64",
        "extra": "Float64",
        "mta_tax": "Float64",
        "tip_amount": "Float64",
        "tolls_amount": "Float64",
        "ehail_fee": "Float64",
        "improvement_surcharge": "Float64",
        "total_amount": "Float64",
        "payment_type": "Int64",
        "trip_type": "Int64",
        "congestion_surcharge": "Float64",
    },
    "fhv": {
        "dispatching_base_num": "string",
        "PUlocationID": "Int64",
        "DOlocationID": "Int64",
        "SR_Flag": "Int64",
        "Affiliated_base_number": "string",
    },
}

taxi_parse_dates = {
    "yellow": ["tpep_pickup_datetime", "tpep_dropoff_datetime"],
    "green": ["lpep_pickup_datetime", "lpep_dropoff_datetime"],
    "fhv": ["pickup_datetime", "dropOff_datetime"],
}
