triggers:
- envs: []
  last_enabled_at: 2024-02-26 02:44:16.125866+00:00
  name: yellow_2019
  pipeline_uuid: taxi_to_gcs
  schedule_interval: '@once'
  schedule_type: time
  settings: {}
  sla: null
  start_time: 2024-02-25
  status: active
  variables:
    service: yellow
    source: backup
    year: 2019
- envs: []
  last_enabled_at: 2024-02-26 02:46:26.095154+00:00
  name: green_2019
  pipeline_uuid: taxi_to_gcs
  schedule_interval: '@once'
  schedule_type: time
  settings: {}
  sla: null
  start_time: 2024-02-25
  status: active
  variables:
    service: green
    source: backup
    year: 2019
- envs: []
  last_enabled_at: 2024-02-26 02:47:56.625592+00:00
  name: fhv_2019
  pipeline_uuid: taxi_to_gcs
  schedule_interval: '@once'
  schedule_type: time
  settings: {}
  sla: null
  start_time: 2024-02-25
  status: active
  variables:
    service: fhv
    source: backup
    year: 2019
- envs: []
  last_enabled_at: 2024-02-26 02:47:56.649377+00:00
  name: yellow_2020
  pipeline_uuid: taxi_to_gcs
  schedule_interval: '@once'
  schedule_type: time
  settings: {}
  sla: null
  start_time: 2024-02-25
  status: active
  variables:
    service: yellow
    source: backup
    year: 2020
- envs: []
  last_enabled_at: 2024-02-26 02:47:56.671717+00:00
  name: green_2020
  pipeline_uuid: taxi_to_gcs
  schedule_interval: '@once'
  schedule_type: time
  settings: {}
  sla: null
  start_time: 2024-02-25
  status: active
  variables:
    service: green
    source: backup
    year: 2020
