[project]
name = "01-docker-sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "niquests>=3.14.0",
    "polars[pandas]>=1.27.1",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.40",
]
