[project]
name = "01-docker-sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "polars[pandas]>=1.25.0",
  "psycopg2-binary>=2.9.10",
  "requests>=2.32.3",
  "sqlalchemy>=2.0.39",
]
