services:
  magic:
    build:
      context: .
      dockerfile: Dockerfile
    command: mage start ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}-magic
    env_file:
      - .env
    environment:
      - USER_CODE_PATH=/home/src/${PROJECT_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "6789:6789"
    volumes:
      - .:/home/src:rw
      - ../../01-docker-terraform/02-terraform-gcp/keys/google_credentials.json:${GOOGLE_APPLICATION_CREDENTIALS}:ro
    restart: on-failure:5
  postgres:
    image: postgres:14
    restart: on-failure
    container_name: ${PROJECT_NAME}-postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
