blocks:
- all_upstream_blocks_executed: true
  color: teal
  configuration:
    file_source:
      path: custom/web_to_postgres.py
  downstream_blocks: []
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: web_to_postgres
  retry_config: null
  status: not_executed
  timeout: null
  type: custom
  upstream_blocks: []
  uuid: web_to_postgres
cache_block_output_in_memory: false
callbacks: []
concurrency_config: {}
conditionals: []
created_at: '2024-02-26 15:52:08.012591+00:00'
data_integration: null
description: null
executor_config: {}
executor_count: 1
executor_type: null
extensions: {}
name: taxi_to_postgres
notification_config: {}
remote_variables_dir: null
retry_config: {}
run_pipeline_in_one_process: false
settings:
  triggers: null
spark_config: {}
tags: []
type: python
uuid: taxi_to_postgres
variables:
  batch_size: 64000
  is_replace: true
  service: yellow
  source: backup
  year: 2019
variables_dir: /home/src/mage_data/magic_zoomcamp
widgets: []
